language: node_js
node_js:
  - "12.0"
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - npm install
  - npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "1//0gZjihefmHZxsCgYIARAAGBASNwF-L9IrNzY415nTR9_SIHNky8O7M-hPO1S_b-L4dZwDdDRDw_YIPBcrVT7ydKMvTjAXsDE0cXw"
